### ISSUE TITLE
[Feature Request] Programmer socks

### ISSUE THREAD

**Issue by DagothUrTheFalse** [MayaqqDev/Estrogen#1]
Please add thigh high programming socks for the proper gamer experience. Razer brand cat ear headphones may also help.

**Comment by MayaqqDev** [comment]
Ok

**Comment by MayaqqDev** [comment]
:3

**Comment by naomieow** [comment]
YES

**Comment by R3Ked** [comment]
wearing them should grant you double dash abilities (but also be really hard to craft to balance it)

**Comment by jadeiseepy** [comment]
btw, it seems like there's a mod that adds programmer socks over [here](https://www.curseforge.com/minecraft/mc-mods/bluies-thigh-high-mod), no fabric support tho 3:

**Comment by MayaqqDev** [comment]
Added next update!
