### ISSUE TITLE
Ender IO tank recipe issue

### ISSUE THREAD

**Issue by ferriarnus** [MayaqqDev/Estrogen#103]
It seems a mistake was made for the Ender IO tank recipe for the [estrogen pill](https://github.com/MayaqqDev/Estrogen/blob/architectury-1.20.1/forge%2Fsrc%2Fmain%2Fresources%2Fdata%2Festrogen%2Frecipes%2Fenderio%2Ftank_fill%2Festrogen_pill.json). Instead of `Amount` and `FluidName`, it should be `amount` and `fluid`, like [black_concrete](https://github.com/Team-EnderIO/EnderIO/blob/dev/1.20.1/src/generated/resources/data/enderio/recipes/tank_fill/black_concrete.json). Would it be possible to fix it as it causes a crash for users, see Team-EnderIO/EnderIO#654 ?

**Comment by MayaqqDev** [comment]
dammit

**Comment by MayaqqDev** [comment]
Fixed.
