### ISSUE TITLE
Game crash upon rendering a Centrifuge

### ISSUE THREAD

**Issue by RepeatGitHub** [MayaqqDev/Estrogen#105]
**Version**: Fabric 1.18.2

**Explanation of what happened**: I was playing the game, placed a Centrifuge under a cogwheel instead of to the side of it, and then the game crashed. I am no longer able to open the world without it crashing.

**Log Link**: [here](https://mclo.gs/O6mqDFh)

**Comment by RepeatGitHub** [comment]
The below is basically a recreation of what I placed in. When I placed the Centrifuge under the rightmost cogwheel, the game crashed instantly, and the same exact thing happened in that I cannot join the world anymore.
![2024-06-18_11 57 13](https://github.com/MayaqqDev/Estrogen/assets/48736123/41eaf23f-19c9-4d63-a2dc-053bfcda0299)

**Comment by MayaqqDev** [comment]
Fixed
