### ISSUE TITLE
Crash on fabric server with the latest version (4.2.8)

### ISSUE THREAD

**Issue by tsgit32** [MayaqqDev/Estrogen#107]
Hi there!!

There's an issue with the latest Estrogen mod version **(4.2.8)** on fabric servers. Everytime i try to start the server there's an error "`Could not execute entrypoint stage 'main' due to errors, provided by 'estrogen'!` ".

I created another fabric server with only the mod and its dependencies to see if it was an incompatibility with other mods but same issue (all Estrogen's dependencies are up to date). So i tried to start the server with **Estrogen 4.2.7** and this time it worked! 

Here's the full error log i got with the **4.2.8** version : https://pastebin.com/uTuTdiaq

**Comment by r1sk01** [comment]
@MayaqqDev bump.

**Comment by MayaqqDev** [comment]
use previous version for now

**Comment by tsgit32** [comment]
fixed with 4.2.9
