### ISSUE TITLE
Removing cookies from Cookie Jar fails when there is a full stack of cookies in player inventory

### ISSUE THREAD

**Issue by mpnordland** [MayaqqDev/Estrogen#108]
estrogen mod version: v4.2.7+1.20.1-fabric

How to reproduce:

1. Be in survival mode
2. Place down a cookie jar
3. Have at least 1 full stack of cookies and a few extra in player inventory
4. Put cookies in the jar till you have 1 full stack of cookies in player inventory (no other cookies of the type inserted into the cookie jar)
5. Right click on cookie jar with an empty hand

Expected behavior:
Cookies will be removed from the jar and placed in the selected hot bar slot.

Actual behavior:
No cookies are added to the player inventory (From what I can tell, no cookies are removed from the cookie jar but I did not verify that)

Note that cookies *can* be removed if there are no cookies or there is a stack with fewer than 64 cookies in the player inventory.

**Comment by MayaqqDev** [comment]
Fixed.
