### ISSUE TITLE
[suggestion] dash and dream blocks dampen fall damage

### ISSUE THREAD

**Issue by dotevie** [MayaqqDev/Estrogen#113]
i think it would be neat if active dream blocks and the dash effect both dampened your fall, it would make movement a lot more fun without having to worry if you'll die of fall damage after you dash high into the air :3

**Comment by omoaubs** [comment]
the dash does dampen your fall a bit, I think the same effect as like feather falling 1? i do agree that they both should be either heightened or nullified though

**Comment by MayaqqDev** [comment]
There will be a more creative way to disable fall damage with estrogen, do not worry.
