### ISSUE TITLE
Multiple People using patches breaks the other's girl power effect

### ISSUE THREAD

**Issue by torturedbymemes** [MayaqqDev/Estrogen#117]
After giving an estrogen patch to a friend as a gift and having her put it on, it proceeded to break my ability to dash several seconds later as I also wear the patch, notable by the blue overlay on my screen staying and my uh.. big naturals popping out of existence. Re-equipping the patches does not fix the issue, as it will break the other person's dash ability several seconds later.
The "girl power" effect is still present in UI, but anything related to it will not work.
This bug occurs with stacked patches and single patches.

**Comment by MayaqqDev** [comment]
what minecraft version? and mod version

**Comment by torturedbymemes** [comment]
Minecraft Version is 1.19.2 and it's happened on mod versions 4.1.1 and 4.1.0

**Comment by MayaqqDev** [comment]
Fixed in 1.20.1 on a new update, sadly 1.19.2 support is getting dropped... if no one wants to port the fix.

**Comment by juuyokka** [comment]
@MayaqqDev Could you share which commit fixed it in 1.20.1? I could see if I can backport it to 1.19.2. It looks like 3a0088d might be the fix, but I'm not 100% sure.
