### ISSUE TITLE
[Issue] Weird vingettes

### ISSUE THREAD

**Issue by valbuilds** [MayaqqDev/Estrogen#13]
![image](https://github.com/MayaqqDev/Estrogen/assets/69707286/dc4e17b8-d5a5-4d18-869c-9e39c0a5b559)
![image](https://github.com/MayaqqDev/Estrogen/assets/69707286/062b95d6-6492-43e8-b377-8268d19db80f)

Mods:
![image](https://github.com/MayaqqDev/Estrogen/assets/69707286/394be3cd-77d2-46e9-9a3b-3dd151d4aed9)

**Comment by valbuilds** [comment]
after an hour of testing i have figured it out it was exordium causing the issue

**Comment by MayaqqDev** [comment]
I should go through my notifications more! Sorry! I will figure out if there is a fix thank you. Exordium seems to be a bit buggy when not playing on vanilla sadly.
