### ISSUE TITLE
Breaking mipmaps?

### ISSUE THREAD

**Issue by chmonyasik** [MayaqqDev/Estrogen#130]
Noticed that mipmaps seem to be downgraded in quality when using this mod, but maybe the problem is in necromancer api.

Estrogen: 4.2.10
Fabric: 0.15.11
Minecraft: 1.20.1
GPU: RTX 2060

Without mod:

![image](https://github.com/user-attachments/assets/ac6036cc-c43a-48af-893a-d3d7f8be733f)

With mod:

![Screenshot_10](https://github.com/user-attachments/assets/b92569eb-72f9-47a6-9281-878ac556c851)

**Comment by chmonyasik** [comment]
You can see better when you're moving, it's not a big problem, but this problem is present in many mods, it overlaps and in general mipmaps breaks more and more.

![image](https://github.com/user-attachments/assets/ceb91096-086d-43ce-b9a6-d5ef0d968269)

**Comment by 800020h** [comment]
search `latest.log` for mipmap to see what's causing it

**Comment by ElenaNya** [comment]
> search `latest.log` for mipmap to see what's causing it

fixed
![blank_lava_flow](https://github.com/user-attachments/assets/4c1c3195-f6ad-4928-81d0-4b54694617c0)
![image](https://github.com/user-attachments/assets/11604e29-885d-43a2-bae3-672b1792e3dc)

**Comment by chmonyasik** [comment]
seems like I managed to fix it.
![image](https://github.com/user-attachments/assets/9130959f-2ff3-48ad-9c21-844c093b44a7)

![blank_lava_flow](https://github.com/user-attachments/assets/40be9dc9-9a91-44de-8279-2e06d6f34c39)

**Comment by chmonyasik** [comment]
*
![blank_lava_flow](https://github.com/user-attachments/assets/660556a5-067b-4654-b38a-c545da5ffd73)

**Comment by MayaqqDev** [comment]
YOU ARE IN LUCK! This is getting fixed next update!
