### ISSUE TITLE
Custom Armor data documentation unclear

### ISSUE THREAD

**Issue by Lele8605** [MayaqqDev/Estrogen#131]
I've been trying to make Create: Stuff and Additions jetpacks work with the mod's chest feature, but many things are unclear:
1. Does the recourcepack need to be seperate or in the mod's jar file
2. How the UV's work. I know this is probably a me problem but I cannot figure out how it works for the life of me
3. How the general structure should look like, where the textures need to be etc...

I know most of these are probably just me being dumb, but I'd appreciate the help

**Comment by MayaqqDev** [comment]
Hey so, first, thanks for the feedback! The feature is not in any released version of the mod, though, it will be soon, just fyi.

The resource pack works as any other resource location, can be both in mods jar or separate, it's like any other file like a model file.


 The uv is basically location in the texture file, take it as coordinates in the 2D plain, take the example to look that it takes part of the texture.

Again, look at the examples

**Comment by Lele8605** [comment]
Thank you for your answer, will be looking forward to the update!
