### ISSUE TITLE
Dream block became a white void

### ISSUE THREAD

**Issue by kohtalee0910** [MayaqqDev/Estrogen#138]
![image](https://github.com/user-attachments/assets/3ae0cba2-c6a3-4d5b-bfcd-1172491e1acb)
and this even happens without embeddium or any other rendering thing so yea

sorry if you all are already working on this but in case you're not here it is

**Comment by invokekitty** [comment]
are you using a dev version? this looks like an incomplete version of the new dream block

**Comment by MayaqqDev** [comment]
not reproducible, if reproduced please reopen/make a new issue.
