### ISSUE TITLE
Centrifuge not working at config value when changed below 256RPM

### ISSUE THREAD

**Issue by Flyer173** [MayaqqDev/Estrogen#145]
Hello,
I'm having an issue where the centrifuge won't make liquid estrogen at the RPM value I set when I change the required value in the config, after restarting. The centrifuge will spin, but only make liquid estrogen when the speed is at 256RPM, nothing less. I recorded a video that should illustrate the issue. Am I misunderstanding the config file?
https://github.com/user-attachments/assets/f6db04e1-d20f-426e-b9f3-130355f0b63f

**Comment by MayaqqDev** [comment]
fixed in https://github.com/MayaqqDev/Estrogen/commit/eb508e24141b536407f6d460b7aa7d7e4a19ae87 sorry for the wait
