### ISSUE TITLE
what are these called

### ISSUE THREAD

**Issue by TheBearodactyl** [MayaqqDev/Estrogen#151]
what the hell are the little flaps called that're shown in this gif from the wiki

![356011783-64570ffc-ebc6-4b17-88f5-4996f32b5d07](https://github.com/user-attachments/assets/2b9ca620-0de5-4738-ba47-8910eeeac49e)

**Comment by invokekitty** [comment]
funnels

**Comment by MayaqqDev** [comment]
Answered by sery

**Comment by TheBearodactyl** [comment]
thanks
