### ISSUE TITLE
version 9G9RyFd6 ( Create: Estrogen 3.0.3+1.19.2)causes the game to crash at initialization

### ISSUE THREAD

**Issue by pokeyt59** [MayaqqDev/Estrogen#18]
here is the log file
[Latest log.txt](https://github.com/MayaqqDev/Estrogen/files/13205788/Latest.log.txt)

**Comment by MayaqqDev** [comment]
Can't find anything about the crash, but estrogen isn't on the newest version. So please provide a crash log and before that update your mods.

**Comment by MayaqqDev** [comment]
Stale issue.
