### ISSUE TITLE
[Forge 1.20.1] Crash "Can't find part boobs

### ISSUE THREAD

**Issue by LenKagamine** [MayaqqDev/Estrogen#190]

**Comment by LenKagamine** [comment]
Sorry, my finger slipped and posted before I could finish the report. The game crashes on startup, here's the report.
https://gist.github.com/LenKagamine/6ea467081e4fdeb34bf703f8d4eb36ec

**Comment by MayaqqDev** [comment]
Fixed in next release (hopefully), right now just update your mods and loader please!
