### ISSUE TITLE
Molten Slime recipe clashes with Create Stuff & Additions

### ISSUE THREAD

**Issue by EBTheHero** [MayaqqDev/Estrogen#193]
The Molten Slime recipe from Create: Estrogen uses the heated mixer to create balls and molten slime.
The Magma Cream recipe from [Create Stuff and Additions](https://www.curseforge.com/minecraft/mc-mods/create-stuff-additions) also uses the heated mixer to create Magma Cream.

When using the mixer with slime, the recipe from Create Stuff And Additions has priority and magma cream is created. One workaround is to filter the recipe on the mixer my placing balls. But you have to cheat to give the item as otherwise it is impossible to aquire it.

**Comment by 800020h** [comment]
can you use a deny list filter for magma cream?

**Comment by MayaqqDev** [comment]
> can you use a deny list filter for magma cream?

yeah but that is not a good solution.

I will try and get this fixed but I don't know how much I can do. We will see, though this is a low priority issue.

**Comment by MayaqqDev** [comment]
Yeah there is no good way to solve this, just use a filter please or dont use create stuff and additions.
