### ISSUE TITLE
[Feature Request] config flag for infinite air dashes

### ISSUE THREAD

**Issue by dot166** [MayaqqDev/Estrogen#194]
similar to how that feature works in the Celeste assist mode

**Comment by MayaqqDev** [comment]
A thing already

**Comment by dot166** [comment]
Was it added after the last release?

**Comment by MayaqqDev** [comment]
There should be like a "minigame" setting in the common config to enable infinite girl power

**Comment by dot166** [comment]
I have found it now, Thank You.
