### ISSUE TITLE
[Fabric 1.20.1] Breast growth seems to de-sync at some point

### ISSUE THREAD

**Issue by FoxySophie** [MayaqqDev/Estrogen#195]
We're using the mod on our server and noticed that at some point the breast growth seems to desync for other players. You can still see the breasts on yourself, but other players are flat even though they have the buff. It seems to get fixed after logging out and back in.

Minecraft 1.20.1
Fabric 0.16.5
Create Estrogen 4.2.10

![image](https://github.com/user-attachments/assets/fba489f3-e692-401e-b169-9e530e4e97b6)

**Comment by MayaqqDev** [comment]
Will be fixed in next release I THINK! If it does not, please reopen
