### ISSUE TITLE
Estrogen Patch ticks twice as fast as it should

### ISSUE THREAD

**Issue by FoxySophie** [MayaqqDev/Estrogen#197]
My friends and I noticed that the Estrogen Patch seems to run out a lot faster than we think it should, so I set up a fresh 1.20.1 instance with Fabric 0.16.5 and Create Estrogen 4.2.10 to test it.
I set the patchDrainAmount to 20, which to my understanding means it should drain 1mB every 20 ticks, ie 1 second. But it is definitely going at least twice as fast, as can be seen here:

https://github.com/user-attachments/assets/1bdc0909-9040-4d7d-b163-0f4b3f554045

**Comment by MayaqqDev** [comment]
Already fixed in the next update! (4.3.0) which will be released soon.
