### ISSUE TITLE
[BUG] Curse of Uwufying is tragically limited to ASCII

### ISSUE THREAD

**Issue by ChlorideCull** [MayaqqDev/Estrogen#204]
**Describe the bug**
The "Curse of Uwufying" enchant tragically does not apply properly to words that contain non-ASCII letters.

**To Reproduce**
1. Equip a helmet with "Curse of Uwufying" applied.
2. Post `unicode suppört` in chat.
3. Notice that the text says `U-UNICOWODE SUPPÖWT >w<`, missing the second "stutter"

**Expected behavior**
The text should say "U-UNICOWODE S-SUPPÖWT >w<"

**Desktop (please complete the following information):**
 - OS: Windows 10

**Game log/Crash Report:**
N/A

**Additional context**
I'm fairly certain the issue is in these regexes, which use `a-zA-Z` - most likely the appropriate replacement is `\p{Ll}\p{Lu}`, which is all unicode letters that are either uppercase or lowercase.
https://github.com/MayaqqDev/Estrogen/blob/66ae7862e0cf71e1a536615bcc48eebd4b95fad0/common/src/main/java/dev/mayaqq/estrogen/client/features/UwUfy.java#L60-L66

**Comment by MayaqqDev** [comment]
oh no. will fix! thanks!
