### ISSUE TITLE
Readme's "Additional features" list isn't compatible with light mode

### ISSUE THREAD

**Issue by Architector4** [MayaqqDev/Estrogen#205]
I was reading through the readme and saw this:
![image](https://github.com/user-attachments/assets/7d9ebc49-141f-4446-960c-4a455313f408)

I assumed a big empty space isn't the intent, and indeed, there's a completely white :3 there lmao

**Comment by MayaqqDev** [comment]
LMFAO

**Comment by MayaqqDev** [comment]
ITs a secret

**Comment by Architector4** [comment]
aaaaaaaaaAAAAAAAAAAAAAAAA

can't believe my estroger has fallen to security by obscurity smh

**Comment by MayaqqDev** [comment]
fixed
