### ISSUE TITLE
Disabling the chest feature in the configuration removes existing chest.

### ISSUE THREAD

**Issue by FractalGeodes** [MayaqqDev/Estrogen#21]
Title basically sums it up. We have existing chest configuration in our skin, but we don't really like how the integration behaves (*it actually gives us a bit of dysphoria rather than euphoria*) but when we disable it, the existing feature on our skin is overwritten and essentially removed when the estrogen effect is active.

Reproduction steps:
1. Have an ears skin with chest configuration set.
2. Disable chest feature in the estrogen config.
3. Apply the Girl Power status effect

Expected Result:
- Existing chest configuration is unchanged
Actual Result:
- Chest configuration is overwritten and visually removed.

**Comment by MayaqqDev** [comment]
Does this mean that it removes the ears chest feature too when disabled?

**Comment by FractalGeodes** [comment]
Essentially, yes. I don't know why I worded it so weirdly :catplush:

**Comment by MayaqqDev** [comment]
ohh, my bad! I think I just dorked up the logic by accident! Will fix!

**Comment by MayaqqDev** [comment]
Now looking at it, I didn't even account for it! Thank you for pointing it out, will fix next update
