### ISSUE TITLE
[Feature Request] Allow buff duration to be configurable

### ISSUE THREAD

**Issue by lord-ruby** [MayaqqDev/Estrogen#210]
add configuration option for the length of the girl power buff provided by each source

**Comment by MayaqqDev** [comment]
Hm, good idea!

**Comment by MayaqqDev** [comment]
Where and for what everything should this be?

**Comment by lord-ruby** [comment]
adjusting the duration of the buff provided by the pills was the main thing i had in mind, otherwise im unsure of what you mean

**Comment by MayaqqDev** [comment]
done
