### ISSUE TITLE
Make a compat to CameraOverhaul mod

### ISSUE THREAD

**Issue by Lostaresto** [MayaqqDev/Estrogen#214]
Dash doesnt work with this mod, camera just glitches
I think this mod will perfectly fit with your addon

**Comment by MayaqqDev** [comment]
I am confused on why that would happen, it just changes your velocity.

**Comment by TheRobbie73** [comment]
i was unable to find any glitches with the camera while dashing
1.20.1 Fabric
Camera Overhaul 1.4.1
Create: Estrogen 4.3.1

**Comment by MayaqqDev** [comment]
Closing as this is an issue specific to your instance.
