### ISSUE TITLE
Compat with Elytra Slot

### ISSUE THREAD

**Issue by LenKagamine** [MayaqqDev/Estrogen#215]
When the mod Elytra Slot is installed alongside Create: Estrogen, the Rosy Maple Elytra should be able to be put in the 'back' Curios slot like the regular elytra.

**Comment by MayaqqDev** [comment]
Good idea I think

**Comment by dot166** [comment]
is this working for anyone else, in 4.3.2 (which has this fix), i still cannot put the Rosy Maple Elytra in the 'back' Curios slot

**Comment by MayaqqDev** [comment]
> is this working for anyone else, in 4.3.2 (which has this fix), i still cannot put the Rosy Maple Elytra in the 'back' Curios slot

Install the elytra slot mod for that.

**Comment by dot166** [comment]
> > is this working for anyone else, in 4.3.2 (which has this fix), i still cannot put the Rosy Maple Elytra in the 'back' Curios slot
> 
> Install the elytra slot mod for that.

I have it installed, and it is still not working
