### ISSUE TITLE
[BUG] After adding Create: Estrogen me and my friend are no long able to log into our server.

### ISSUE THREAD

**Issue by Ganpan14O** [MayaqqDev/Estrogen#219]
**Describe the bug**

**To Reproduce**
1. Put the mods from https://drive.google.com/file/d/1wYVr-gzUmPV_itITQhMaqhWA5p3c0aTC/view?usp=drive_link or the same mod list on the client
2. Put https://drive.google.com/file/d/1NfG4EOwkXIjtKIwR5b6RFpbmkoTdsM1Y/view?usp=drive_link or the same mod list on the server
3. Attempt to connect to the server

**Expected behavior**
It is expected that you can connect to a running server with a compatible mod list.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 4.3.1

**Game log/Crash Report:**
- Server: https://mclo.gs/k8Id1eG
- Me: https://mclo.gs/NLMwcJr
- Friend: https://mclo.gs/5iRXvhO

**Additional context**
Both me and my friend's logs are included as the disconnection reason was different between us

**Comment by MayaqqDev** [comment]
Server seems to be missing the mod, sorry for being so late, marked as close because this is not an estrogen issue, you just either didnt put the mod in the server mods folder or didnt restart the server.

**Comment by Ganpan14O** [comment]
Server log line 228: https://mclo.gs/k8Id1eG#L228

**Comment by Ganpan14O** [comment]
It appears this issue is a result of an incompatibility with Slice of Life: Apple Pie edition and this mod. The line I linked to a while ago is the line that says the mod is being loaded on the server, that is not the issue.

**Comment by Ganpan14O** [comment]
No idea if this was actually fixed from another report or is simply no longer an issue but it seems like it's fixed. I have a theory it may have been that the config of SOL Apple Pie uses an improper id for the movement speed attribute by default
