### ISSUE TITLE
More pride socks

### ISSUE THREAD

**Issue by TheBiPerson** [MayaqqDev/Estrogen#221]
**Describe the idea you'd like**
More flag socks! Specifically the AroAce & Abrosexual flag, but in general I feel more socks would be a great addition!

**Additional context**
:3

**Comment by invokekitty** [comment]
You can add them via resource and data pack :3 However idk if adding even more default socks is a good idea

**Comment by TheBiPerson** [comment]
oh cool! sorry i didnt see that, could you show me where to find out how to make the datapack for them?

**Comment by invokekitty** [comment]
It isn't exactly written anywhere but im gonna send an example datapack/resourcepack in the hue discord server

**Comment by TheBiPerson** [comment]
thank you sm! my discord is TheBiPerson, so @ me whenever :3 thank you again and please tyt

**Comment by MayaqqDev** [comment]
Closing as not planned.
