### ISSUE TITLE
[BUG] Mof Elytra doesn't De-Render capes if skin has one

### ISSUE THREAD

**Issue by ChaosDogG** [MayaqqDev/Estrogen#222]
**Describe the bug**
When you put on the moth elytra, if you have a cape available and wearing it, it will not be turned off when the elytra is put on

**To Reproduce**
1. put on cape
2. put on elytra

**Expected behavior**
The cape should be turned off at the very least

**Screenshots**
none were taken at this time, but there should be vods of this on our twitches towards the end http://twitch.tv/billyp673 and http://twitch.tv/chaosdog1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser OperaGX
 - Version (idk wut needs to be here, does this mean mod version or browser version?)

**Game log/Crash Report:**
- [idk what would be found since it's rendering but here ya go](https://mclo.gs/gixeri7)

**Additional context**
he was using the migrator cape, but i do believe it will happen w any cape

**Comment by MayaqqDev** [comment]
Idk if to consider this a bug or a feature, but sure, i will disable it.
