### ISSUE TITLE
[BUG] Create Estrogen does not load with custom modpack on latest version

### ISSUE THREAD

**Issue by Capt-Alex** [MayaqqDev/Estrogen#226]
Create: Estrogen does not load on start when on the latest version.

**To Reproduce**
1. Start Minecraft with custom modpack
2. "Create: Estrogen (estrogen) has failed to load correctly"

**Expected behavior**
Create: Estrogen should be loading

**Screenshots**
![image](https://github.com/user-attachments/assets/cad56366-a711-45f7-bbc5-1abd9ca741c6)

**Desktop:**
 - OS: [Windows 10]
 - Browser [Firefox]
 - Version [22H2]

**Game log/Crash Report:**
- https://mclo.gs/hvhMMle

**Additional context**
- Using both recent versions of Create & Create: Estrogen 0.5.1j/4.3.1
- Version 4.2.10 and below work
- Using Prism Launcher to launch Minecraft

**Comment by invokekitty** [comment]
are you also playing with rubinated nether?

**Comment by Capt-Alex** [comment]
> are you also playing with rubinated nether?

Yes, I am.
