### ISSUE TITLE
[Feature Request] possible integration with Wildfire's Female Gender Mod

### ISSUE THREAD

**Issue by TyoAtrosa** [MayaqqDev/Estrogen#33]
Their player renderer has more detailed and configurable features, and I was wondering if it might be possible to add a hook into that mod to allow estrogen to affect boob growth using that mod instead.

**Comment by MayaqqDev** [comment]
Maybe, will keep this in mind. Right now just go into the config and disable the estrogen boobs.

**Comment by MayaqqDev** [comment]
This is basically useless now, closing due to not relevant.
