### ISSUE TITLE
Crash on dedicated server load

### ISSUE THREAD

**Issue by Ebkrem** [MayaqqDev/Estrogen#42]
Mod does not load correctly when ran on a dedicated server.
Using MC Server Soft to run server.
Mod *does* load correctly client-side and when loading a single player world.

Also crash log issues link incorrectly listed as: https://github.com/mayaqq/Estrogen/issues
(Incorrect link has mayaqq rather than MayaqqDev)

From attached log:
Exception message: java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/ClientLevel for invalid dist DEDICATED_SERVER
[crash-2024-01-22_00.50.51-fml.txt](https://github.com/MayaqqDev/Estrogen/files/14003443/crash-2024-01-22_00.50.51-fml.txt)

**Comment by MayaqqDev** [comment]
Probably fixed already. If not open new issue.
