### ISSUE TITLE
Game crash when applying Girl Power effect

### ISSUE THREAD

**Issue by gingershaped** [MayaqqDev/Estrogen#43]
Appears to stem from `EstrogenKeybinds.register()` not being called during the mod setup process?
[crash-2024-01-22_15.52.09-client.txt](https://github.com/MayaqqDev/Estrogen/files/14015389/crash-2024-01-22_15.52.09-client.txt)

**Comment by MayaqqDev** [comment]
what how what why 😭

**Comment by MayaqqDev** [comment]
Fixed.
