### ISSUE TITLE
Game crashes when trying to render boobs on ice and fire dragon armour.

### ISSUE THREAD

**Issue by Ninty9** [MayaqqDev/Estrogen#50]
[crash-2024-02-10_16.05.11-client.txt](https://github.com/MayaqqDev/Estrogen/files/14229628/crash-2024-02-10_16.05.11-client.txt)

Throws a ResourceLocationException: Non [a-z0-9_.-] character in namespace of location: textures/models/armor/iceandfire:armor_dragon_scales9_layer_1.png

Even if this isnt fixable it might be best to make sure it doesnt completely crash when it cant find the armour texture.

**Comment by MayaqqDev** [comment]
Update the mod please, fixed in newer versions
