### ISSUE TITLE
Estrogen patch stops working until re-application.

### ISSUE THREAD

**Issue by artifishvr** [MayaqqDev/Estrogen#53]
MC Version: 1.19.2
Loader: Quilt 0.23.1
Multiplayer, dedicated server
[Mod List](https://pastebin.com/sZpCxUAU)

Here's a clip of the bug happening (volume warning - my microphone volume was really high for some reason, i swear i don't hit my keys that hard)
https://github.com/MayaqqDev/Estrogen/assets/59352535/ae169ad5-f567-404b-a959-a7ccd075ba67
No errors in client or server logs.

**Comment by jadeiseepy** [comment]
btw this seems to be fixed as of `63a8e32`, don't know the exact commit

**Comment by MayaqqDev** [comment]
Yep fixed
