### ISSUE TITLE
UwUfied text remains after leaving to main menu

### ISSUE THREAD

**Issue by WcieloMnie** [MayaqqDev/Estrogen#55]
Player can observe UwUfied text after leaving the world with ":3" item in inventory.

**Steps to reproduce:**

1.  Launch the game
2.  Obtain ":3" item
3.  Put it into your Inventory
4.  Leave the world
5.  Observe that everything in main menu is UwUfied

**Notes:**

- Joining another world will reverse UwU curse.
![image_2024-02-21_014805447](https://github.com/MayaqqDev/Estrogen/assets/160683625/de6da914-af81-484c-8fe5-d1886cfe955c)
![image_2024-02-21_014934209](https://github.com/MayaqqDev/Estrogen/assets/160683625/b59b11e2-0cab-40e0-a9db-0e98d4dbe316)

**Comment by RemagOfficial** [comment]
its a feature, right maya?

**Comment by MayaqqDev** [comment]
Lol

**Comment by a55uka** [comment]
I see this as only a feature, no bugs here

**Comment by MayaqqDev** [comment]
Intended behaviour (surely)
