### ISSUE TITLE
Inappropriate use of minecraft:water tag

### ISSUE THREAD

**Issue by andrea-feather** [MayaqqDev/Estrogen#59]
All fluids in this mod have the `minecraft:water` tag, presumably to make them automatically useable in buckets and tanks. However, a sideeffect is that they can be used _in almost any situation water can._

While it's extremely funny to use estrogen as reactor coolent or use horse piss as the solvent in a distillation, I'm not sure that this is intended behavior. It definitely leads to some unexpected results when viewing recipes in JEI.

**Comment by MayaqqDev** [comment]
Omg lmfao

**Comment by RemagOfficial** [comment]
piss reactor

**Comment by ScoutTheSaneless** [comment]
It's not a bug, it's a feature, lolol
