### ISSUE TITLE
Using the centrifuge crashes the game

### ISSUE THREAD

**Issue by bqyden** [MayaqqDev/Estrogen#62]
upon meeting the requirements for the centrifuge, it crashes the game with an exit code: 255

**Comment by MayaqqDev** [comment]
What version

**Comment by bqyden** [comment]
Latest mod version, minecraft version 1.20.1
[log.txt](https://github.com/MayaqqDev/Estrogen/files/14590840/log.txt)

**Comment by axialeaa** [comment]
Can confirm

**Comment by MayaqqDev** [comment]
Oh right, downgrade create for now. It will be fixed eventually but basically, create decided to break things!

**Comment by axialeaa** [comment]
~~what exactly is the issue?~~ nvm i think i found it. should be fixable by adding `maven { "https://mvn.devos.one/releases" }` to the dependencies because they changed porting lib's maven location to releases from snapshots

**Comment by MayaqqDev** [comment]
That is NOT the issue.

**Comment by axialeaa** [comment]
Ah okay, fair enough. My apologies

**Comment by solonovamax** [comment]
I can attempt to make a quick PR to fix this as I'm currently encountering the same issue (and cba to downgrade bc that means I need to downgrade like 6 other create addons that I manually ported to the latest version myself lmao)

**Comment by solonovamax** [comment]
nvm, seems to be updated in commit ead13c8. I'll just build that from source lol

**Comment by MayaqqDev** [comment]
Fixed in next update.
