### ISSUE TITLE
class access error on mod load forge 1.20.1 mod 4.1.0

### ISSUE THREAD

**Issue by HollyEvergreen** [MayaqqDev/Estrogen#66]
[crash-2024-03-19_15.41.15-client.txt](https://github.com/MayaqqDev/Estrogen/files/14652944/crash-2024-03-19_15.41.15-client.txt)
crash log attached
[TavernPack.zip](https://github.com/MayaqqDev/Estrogen/files/14652959/TavernPack.zip)
curseforge profile attached (sorry i cant help further my expertise is in unity)

**Comment by MayaqqDev** [comment]
Usually when this error appears, it isn't a thing caused by Estrogen but some unrelated error that so happens to put Estrogen right at the top of the stacktrace

**Comment by HollyEvergreen** [comment]
oh ok lemme check the stack trace again if you want i can try to fix it if it is an incompatibility bug ill see what i can do

**Comment by HollyEvergreen** [comment]
sorry for bothering you its working now :|
