### ISSUE TITLE
[Feature Request] Dilator

### ISSUE THREAD

**Issue by xslendix** [MayaqqDev/Estrogen#7]
I think that adding a dilator into the mod would be very cute!!! It can give you like a recharge mechanic into the game or something else!! This would be super empowering :3

**Comment by vlxjack** [comment]
Totally agree! Dilator would be such a wholesome addition,,, especially for the realism side awell!!

**Comment by daiwong28** [comment]
It's such a vital part of life for a trans-woman with a neo-vagina! A must need!! #translivesmatter

**Comment by wanesty** [comment]
bestie why the fuck

edit: not meant to be mean, that's just a bit weird and it was a funny request to make

**Comment by slendidev** [comment]
Just thought it was a good addition >///<

**Comment by MayaqqDev** [comment]
Maybe

**Comment by Gentleman2292** [comment]
pls add :3

**Comment by MayaqqDev** [comment]
Uhhhhhhhhhh

**Comment by pachuco** [comment]
What status effect would dilation even give the player?

**Comment by MayaqqDev** [comment]
hairless

**Comment by Gentleman2292** [comment]
or maybe a uh speed boost

**Comment by slendidev** [comment]
that could work!! but i think recharge would fit in nicely with the existing mod personally~

**Comment by LennyMcLennington** [comment]
Closing this issue is very transphobic in my opinion, as this is a very important feature since us trans folx need to do it every week multiple times a week for the rest of our lives. I'm contacting Quilt Community as we speak consider yourself cancelled 😤😤

**Comment by Wyvest** [comment]
> Closing this issue is very transphobic in my opinion, as this is a very important feature since us trans folx need to do it every week multiple times a week for the rest of our lives. I'm contacting Quilt Community as we speak consider yourself cancelled 😤😤

how's reclaiming from the leftoids going

**Comment by pauliesnug** [comment]
trans rights !! !! !! :3

**Comment by Syz66** [comment]
woaw... trans people

**Comment by wanesty** [comment]
y'all be saying a whole lot about trans "rights" and alike, but what if they wanna do crime ???

i proudly support trans wrongs 😤

**Comment by Syz66** [comment]
> y'all be saying a whole lot about trans "rights" and alike, but what if they wanna do crime ???
> 
> i proudly support trans wrongs 😤

I think trans people should be allowed to commit all non-violent crimes. #TRANSRIGHTS
