### ISSUE TITLE
Centrifuge does not produce estrogen in latest git commit

### ISSUE THREAD

**Issue by solonovamax** [MayaqqDev/Estrogen#73]
When using the latest git commit, the centrifuge will not produce estrogen for some reason.
To power it, I am using a Strong Motor from Create: New Age, set to 256 RPM, with a strong motor extension at 800%, for a total of 16384 su.

I have not tested in a dedicated world with only this mod, however this is happening in my main world. There are no errors (that I noticed) in the log.

**Comment by MayaqqDev** [comment]
Fixed.
