### ISSUE TITLE
Crash in custom modpack - incompatibilities with other mods?

### ISSUE THREAD

**Issue by biomasters2** [MayaqqDev/Estrogen#86]
I'm in the process of making a custom modpack for myself and some friends to play a server on, but if I update Estrogen to a version above 4.1.0 (this version itself works perfectly) the game crashes whenever I try to create a world.

[crash-2024-04-13_11.24.43-client.txt](https://github.com/MayaqqDev/Estrogen/files/14968505/crash-2024-04-13_11.24.43-client.txt)

I don't know how to read crash logs just yet but I see that it mentions a couple other mods, but they worked perfectly fine with previous versions of estrogen.

(this is my first time submitting an issue so let me know if you need any more info)

**Comment by MayaqqDev** [comment]
Unrelated to Estrogen, seems to be an EnderIO issue.
