### ISSUE TITLE
[Feature Request] Option for boobs to be permanent even after Girl Power effect ends

### ISSUE THREAD

**Issue by NthPortal** [MayaqqDev/Estrogen#87]

**Comment by MayaqqDev** [comment]
@PrincessDoreena would this be possible?

**Comment by invokekitty** [comment]
not princessdoreena here but yes this should be possible

**Comment by invokekitty** [comment]
and probably quite easy

**Comment by MayaqqDev** [comment]
Well of course it would be possible, it is more of the fact that she did most of the boob work so its a request if she could do this.
