### ISSUE TITLE
server crashes a bit after it's loaded

### ISSUE THREAD

**Issue by omoaubs** [MayaqqDev/Estrogen#89]
every time i load up my server (via exaroton), it crashes with the error "Exception in server tick loop" about a minute after loading. using 1.20.1 with 4.2.5 version of estrogen.

logs
https://mclo.gs/1IcYzvG

**Comment by S0apyy** [comment]
this also happens on 4.2.4 on my modpack

**Comment by omoaubs** [comment]
could you send your logs here?

**Comment by S0apyy** [comment]
i shouldnt have to as the log is exactly the same except pc specs

**Comment by S0apyy** [comment]
and ive also tested further, the same crash happens on 4.2.0 and above

**Comment by omoaubs** [comment]
I mainly meant for mod complication reasons, run it through mclo.gs if
you’re worried about personal info

**Comment by 800020h** [comment]
a crash log
[crash-2024-04-18_09.35.49-server.txt](https://github.com/MayaqqDev/Estrogen/files/15022893/crash-2024-04-18_09.35.49-server.txt)

**Comment by 800020h** [comment]
I hope that crash log is the same issue
it only seemed to crash once for me

**Comment by 800020h** [comment]
it happened again but much longer after the server started

**Comment by omoaubs** [comment]
it seems to be working as intended now? thoroughly confused

**Comment by MayaqqDev** [comment]
Fixed next version
