### ISSUE TITLE
With some mods that add armor the tits get the untextured purple but on others they aren't untextured

### ISSUE THREAD

**Issue by EmiSunn** [MayaqqDev/Estrogen#95]
I don't know if the immersive armors mod just has compatibility with this mod or it works by random chance, but the fact it it does means that it should theoretically be compatible with all armor from any mod right?

The Warrior Armor Set from the Immersive Armors Mod
![2024-05-02_16 40 44](https://github.com/MayaqqDev/Estrogen/assets/108381224/dc5bc794-a70a-4619-9cf7-d4aec742db50)

The Wandering Magician Armor Set from the Iron's Spellbooks Mod
![2024-05-02_16 41 44](https://github.com/MayaqqDev/Estrogen/assets/108381224/a1f17248-35bf-407b-a5ad-7be487ce23b4)

The Fiery Armor Set from the Twilight Forest Mod
![2024-05-02_16 42 02](https://github.com/MayaqqDev/Estrogen/assets/108381224/4c3a79d5-169a-46a4-bac2-ad69ed4ba6e6)

**Comment by MayaqqDev** [comment]
Fixed next update (well kind of, the other mods need to add their own specific compat, but its just a singular json file in the assets folder.)
