### ISSUE TITLE
Infinite Pools

### ISSUE THREAD

**Issue by The-Pogrammer** [MayaqqDev/Estrogen#97]
In create, pools of liquid > 10,000 blocks are infinite when pulled by a hose pulley. Even if you go into the configs and change the tag thing to "ALLOW_ALL" none of the liquids in this mod will be infinite.

**Comment by MayaqqDev** [comment]
weird

**Comment by TheRobbie73** [comment]
tried this on 1.20.1 on both fabric and forge with 4.3.0 Estrogen and was able to get bottomless supply with the config set to ALLOW_ALL so either its already been fixed or something else is happening to cause your bug

**Comment by MayaqqDev** [comment]
Yeah uh, I looked at the code, it shouldn't block it, this is user error, and considering it doesn't seem to happen to anyone else. I am closing this.
