### ISSUE TITLE
Forge Version Crashing with exit code 1

### ISSUE THREAD

**Issue by lucyamonster** [MayaqqDev/Estrogen#98]
When trying to launch the game with the mod it just crashes with exit code 1. It goes away if you remove the file again.
I have tried versions: 4.2.6+1.20.1, 4.2.7+1.20.1 and 4.2.0+1.20.1.
Is there anything I have forgotten? thanks in advance :3
The Log: [latest.log](https://github.com/MayaqqDev/Estrogen/files/15248423/latest.log)

**Comment by MayaqqDev** [comment]
> [08May2024 13:53:23.409] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
> 	Mod ID: 'resourcefullib', Requested by: 'estrogen', Expected range: '*', Actual version: '[MISSING]'
> 	Mod ID: 'botarium', Requested by: 'estrogen', Expected range: '*', Actual version: '[MISSING]'
> 	Mod ID: 'curios', Requested by: 'estrogen', Expected range: '*', Actual version: '[MISSING]'

probably this
